# Dockerfile for apollo-admin-server

# Build with:
# docker build -t apollo-admin-server:v1.0.0 .

FROM hpy253215039/oraclejdk-skywalking-linux-64:8u221
RUN mkdir -p /apollo-admin-server

ADD ./config/ /apollo-admin-server/
ADD ./jar/1.4.0/ /apollo-admin-server/

# ENV APOLLO_ADMIN_SERVICE_NAME="service-apollo-admin-server.sre"

EXPOSE 8090

CMD ["/apollo-admin-server/scripts/startup-kubernetes.sh"]
